enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
# arch = "arm64-v8a"

[YouTube-Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
# arch = "arm64-v8a"

[Instagram]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"
direct-dlurl = "https://wispy.qzz.io/f/YPfl/com.instagram.android-435.0.0.37.76-384109419_2dpi_16ea7ffdd82e0123366db5cfd68328fa_apkmirror.com_merged.apk"
arch = "arm64-v8a"
